Feature/before asset output callback
cascornelissen/svg-spritemap-webpack-plugin pull request #124
Opened 2020-10-06 08:31 UTC by SowmediaNL

2020-10-21 10:31 UTC, cascornelissen requested changes
Sorry for the late review, apparently I forgot to submit it 🤦🏼‍♂️

2020-10-26 11:19 UTC, SowmediaNL commented on docs/options.md
> +#### `styles.callback` – `'callback'`
Thanks! The change was comitted.

2020-10-26 19:22 UTC, cascornelissen commented
Code LGTM, would you mind squashing your commits into one commit to keep `master` history clean?

2020-11-02 15:11 UTC, SowmediaNL commented
How do we squash the commits? Is that not up to the pull-request merger? I have no options for it in Github.

2020-11-02 15:35 UTC, cascornelissen commented
If you're not sure how to do it manually (you usually do it locally), I'll create a merge commit instead, no problem 👍🏼

2020-11-02 15:36 UTC, cascornelissen approved these changes

2020-11-02 20:45 UTC, merged

2020-11-02 21:24 UTC, cascornelissen commented
This feature was included in release [`3.7.0`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v3.7.0), thanks for your contribution! 🚀